name: Preprocessing Workflow

on:
  push:
    paths:
      - '**/*.py'
      - '.github/workflows/preprocessing.yml'

jobs:
  preprocessing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Automate script
        run: |
          python scripts/Automate.py

